version: '3.8'

services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: docuseal/docuseal:latest
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - docuseal_data:/data/docuseal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=blackender-net"
      - "traefik.http.routers.docuseal.rule=Host(`docuseal.nas`)"
      - "traefik.http.routers.docuseal.entrypoints=web"
      - "traefik.http.services.docuseal.loadbalancer.server.port=3000"
    environment:
      - FORCE_SSL=${FORCE_SSL:-false}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS:-5}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    networks:
      - default
      - blackender-net

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:latest
    restart: unless-stopped
    profiles:
      - standalone-caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}

volumes:
  docuseal_data:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  blackender-net:
    external: true
